// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: section.proto

package sectionservice

import (
	"context"

	"temp/section/rpc/section/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateSectionRequest  = rpc.CreateSectionRequest
	CreateSectionResponse = rpc.CreateSectionResponse
	DeleteSectionRequest  = rpc.DeleteSectionRequest
	DeleteSectionResponse = rpc.DeleteSectionResponse
	Empty                 = rpc.Empty
	GetSectionRequest     = rpc.GetSectionRequest
	SectionListResponse   = rpc.SectionListResponse
	SectionRequest        = rpc.SectionRequest
	SectionResponse       = rpc.SectionResponse
	UpdateSectionRequest  = rpc.UpdateSectionRequest
	UpdateSectionResponse = rpc.UpdateSectionResponse

	SectionService interface {
		CreateSection(ctx context.Context, in *CreateSectionRequest, opts ...grpc.CallOption) (*CreateSectionResponse, error)
		UpdateSection(ctx context.Context, in *UpdateSectionRequest, opts ...grpc.CallOption) (*UpdateSectionResponse, error)
		DeleteSection(ctx context.Context, in *DeleteSectionRequest, opts ...grpc.CallOption) (*DeleteSectionResponse, error)
		ListSections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SectionListResponse, error)
		GetSection(ctx context.Context, in *GetSectionRequest, opts ...grpc.CallOption) (*SectionResponse, error)
	}

	defaultSectionService struct {
		cli zrpc.Client
	}
)

func NewSectionService(cli zrpc.Client) SectionService {
	return &defaultSectionService{
		cli: cli,
	}
}

func (m *defaultSectionService) CreateSection(ctx context.Context, in *CreateSectionRequest, opts ...grpc.CallOption) (*CreateSectionResponse, error) {
	client := rpc.NewSectionServiceClient(m.cli.Conn())
	return client.CreateSection(ctx, in, opts...)
}

func (m *defaultSectionService) UpdateSection(ctx context.Context, in *UpdateSectionRequest, opts ...grpc.CallOption) (*UpdateSectionResponse, error) {
	client := rpc.NewSectionServiceClient(m.cli.Conn())
	return client.UpdateSection(ctx, in, opts...)
}

func (m *defaultSectionService) DeleteSection(ctx context.Context, in *DeleteSectionRequest, opts ...grpc.CallOption) (*DeleteSectionResponse, error) {
	client := rpc.NewSectionServiceClient(m.cli.Conn())
	return client.DeleteSection(ctx, in, opts...)
}

func (m *defaultSectionService) ListSections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SectionListResponse, error) {
	client := rpc.NewSectionServiceClient(m.cli.Conn())
	return client.ListSections(ctx, in, opts...)
}

func (m *defaultSectionService) GetSection(ctx context.Context, in *GetSectionRequest, opts ...grpc.CallOption) (*SectionResponse, error) {
	client := rpc.NewSectionServiceClient(m.cli.Conn())
	return client.GetSection(ctx, in, opts...)
}
