apiVersion: v1
kind: ConfigMap
metadata:
  name: bbs-config
  namespace: temp
data:
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "123456"
  DB_NAME: "bbs-go"
  ETCD_HOSTS: "etcd-svc:2379"
  JWT_SECRET: "this-is-a-secret"
  MQ_HOST: "rabbitmq-svc"
  MQ_PORT: "5672"
  MQ_USER: "guest"
  MQ_PASSWORD: "guest"
