// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: section.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_section_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{0}
}

type SectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	OrderIndex    int64                  `protobuf:"varint,3,opt,name=OrderIndex,proto3" json:"OrderIndex,omitempty"`
	Visibility    bool                   `protobuf:"varint,4,opt,name=Visibility,proto3" json:"Visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionRequest) Reset() {
	*x = SectionRequest{}
	mi := &file_section_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionRequest) ProtoMessage() {}

func (x *SectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionRequest.ProtoReflect.Descriptor instead.
func (*SectionRequest) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{1}
}

func (x *SectionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SectionRequest) GetOrderIndex() int64 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *SectionRequest) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

type SectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	OrderIndex    int64                  `protobuf:"varint,4,opt,name=OrderIndex,proto3" json:"OrderIndex,omitempty"`
	Visibility    bool                   `protobuf:"varint,5,opt,name=Visibility,proto3" json:"Visibility,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionResponse) Reset() {
	*x = SectionResponse{}
	mi := &file_section_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionResponse) ProtoMessage() {}

func (x *SectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionResponse.ProtoReflect.Descriptor instead.
func (*SectionResponse) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{2}
}

func (x *SectionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SectionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SectionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SectionResponse) GetOrderIndex() int64 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *SectionResponse) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

func (x *SectionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SectionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OrderIndex    int64                  `protobuf:"varint,3,opt,name=orderIndex,proto3" json:"orderIndex,omitempty"`
	Visibility    bool                   `protobuf:"varint,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionRequest) Reset() {
	*x = CreateSectionRequest{}
	mi := &file_section_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionRequest) ProtoMessage() {}

func (x *CreateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionRequest.ProtoReflect.Descriptor instead.
func (*CreateSectionRequest) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSectionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSectionRequest) GetOrderIndex() int64 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *CreateSectionRequest) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

type CreateSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       *SectionResponse       `protobuf:"bytes,1,opt,name=Section,proto3" json:"Section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionResponse) Reset() {
	*x = CreateSectionResponse{}
	mi := &file_section_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionResponse) ProtoMessage() {}

func (x *CreateSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionResponse.ProtoReflect.Descriptor instead.
func (*CreateSectionResponse) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSectionResponse) GetSection() *SectionResponse {
	if x != nil {
		return x.Section
	}
	return nil
}

type UpdateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OrderIndex    int64                  `protobuf:"varint,4,opt,name=orderIndex,proto3" json:"orderIndex,omitempty"`
	Visibility    bool                   `protobuf:"varint,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSectionRequest) Reset() {
	*x = UpdateSectionRequest{}
	mi := &file_section_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionRequest) ProtoMessage() {}

func (x *UpdateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSectionRequest) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSectionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSectionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSectionRequest) GetOrderIndex() int64 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *UpdateSectionRequest) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

type UpdateSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       *SectionResponse       `protobuf:"bytes,1,opt,name=Section,proto3" json:"Section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSectionResponse) Reset() {
	*x = UpdateSectionResponse{}
	mi := &file_section_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionResponse) ProtoMessage() {}

func (x *UpdateSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSectionResponse) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSectionResponse) GetSection() *SectionResponse {
	if x != nil {
		return x.Section
	}
	return nil
}

type DeleteSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSectionRequest) Reset() {
	*x = DeleteSectionRequest{}
	mi := &file_section_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSectionRequest) ProtoMessage() {}

func (x *DeleteSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSectionRequest) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSectionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSectionResponse) Reset() {
	*x = DeleteSectionResponse{}
	mi := &file_section_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSectionResponse) ProtoMessage() {}

func (x *DeleteSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSectionResponse) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SectionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SectionResponse     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionListResponse) Reset() {
	*x = SectionListResponse{}
	mi := &file_section_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionListResponse) ProtoMessage() {}

func (x *SectionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionListResponse.ProtoReflect.Descriptor instead.
func (*SectionListResponse) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{9}
}

func (x *SectionListResponse) GetList() []*SectionResponse {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SectionListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectionRequest) Reset() {
	*x = GetSectionRequest{}
	mi := &file_section_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectionRequest) ProtoMessage() {}

func (x *GetSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectionRequest.ProtoReflect.Descriptor instead.
func (*GetSectionRequest) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{10}
}

func (x *GetSectionRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_section_proto protoreflect.FileDescriptor

const file_section_proto_rawDesc = "" +
	"\n" +
	"\rsection.proto\x12\asection\"\a\n" +
	"\x05Empty\"\x88\x01\n" +
	"\x0eSectionRequest\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"OrderIndex\x18\x03 \x01(\x03R\n" +
	"OrderIndex\x12\x1e\n" +
	"\n" +
	"Visibility\x18\x04 \x01(\bR\n" +
	"Visibility\"\xd5\x01\n" +
	"\x0fSectionResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"OrderIndex\x18\x04 \x01(\x03R\n" +
	"OrderIndex\x12\x1e\n" +
	"\n" +
	"Visibility\x18\x05 \x01(\bR\n" +
	"Visibility\x12\x1c\n" +
	"\tCreatedAt\x18\x06 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\a \x01(\tR\tUpdatedAt\"\x8e\x01\n" +
	"\x14CreateSectionRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"orderIndex\x18\x03 \x01(\x03R\n" +
	"orderIndex\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\bR\n" +
	"visibility\"K\n" +
	"\x15CreateSectionResponse\x122\n" +
	"\aSection\x18\x01 \x01(\v2\x18.section.SectionResponseR\aSection\"\x9e\x01\n" +
	"\x14UpdateSectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"orderIndex\x18\x04 \x01(\x03R\n" +
	"orderIndex\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\bR\n" +
	"visibility\"K\n" +
	"\x15UpdateSectionResponse\x122\n" +
	"\aSection\x18\x01 \x01(\v2\x18.section.SectionResponseR\aSection\"&\n" +
	"\x14DeleteSectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x15DeleteSectionResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"Y\n" +
	"\x13SectionListResponse\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.section.SectionResponseR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"#\n" +
	"\x11GetSectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id2\x82\x03\n" +
	"\x0eSectionService\x12N\n" +
	"\rCreateSection\x12\x1d.section.CreateSectionRequest\x1a\x1e.section.CreateSectionResponse\x12N\n" +
	"\rUpdateSection\x12\x1d.section.UpdateSectionRequest\x1a\x1e.section.UpdateSectionResponse\x12N\n" +
	"\rDeleteSection\x12\x1d.section.DeleteSectionRequest\x1a\x1e.section.DeleteSectionResponse\x12<\n" +
	"\fListSections\x12\x0e.section.Empty\x1a\x1c.section.SectionListResponse\x12B\n" +
	"\n" +
	"GetSection\x12\x1a.section.GetSectionRequest\x1a\x18.section.SectionResponseB\x0fZ\r./section/rpcb\x06proto3"

var (
	file_section_proto_rawDescOnce sync.Once
	file_section_proto_rawDescData []byte
)

func file_section_proto_rawDescGZIP() []byte {
	file_section_proto_rawDescOnce.Do(func() {
		file_section_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_section_proto_rawDesc), len(file_section_proto_rawDesc)))
	})
	return file_section_proto_rawDescData
}

var file_section_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_section_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: section.Empty
	(*SectionRequest)(nil),        // 1: section.SectionRequest
	(*SectionResponse)(nil),       // 2: section.SectionResponse
	(*CreateSectionRequest)(nil),  // 3: section.CreateSectionRequest
	(*CreateSectionResponse)(nil), // 4: section.CreateSectionResponse
	(*UpdateSectionRequest)(nil),  // 5: section.UpdateSectionRequest
	(*UpdateSectionResponse)(nil), // 6: section.UpdateSectionResponse
	(*DeleteSectionRequest)(nil),  // 7: section.DeleteSectionRequest
	(*DeleteSectionResponse)(nil), // 8: section.DeleteSectionResponse
	(*SectionListResponse)(nil),   // 9: section.SectionListResponse
	(*GetSectionRequest)(nil),     // 10: section.GetSectionRequest
}
var file_section_proto_depIdxs = []int32{
	2,  // 0: section.CreateSectionResponse.Section:type_name -> section.SectionResponse
	2,  // 1: section.UpdateSectionResponse.Section:type_name -> section.SectionResponse
	2,  // 2: section.SectionListResponse.list:type_name -> section.SectionResponse
	3,  // 3: section.SectionService.CreateSection:input_type -> section.CreateSectionRequest
	5,  // 4: section.SectionService.UpdateSection:input_type -> section.UpdateSectionRequest
	7,  // 5: section.SectionService.DeleteSection:input_type -> section.DeleteSectionRequest
	0,  // 6: section.SectionService.ListSections:input_type -> section.Empty
	10, // 7: section.SectionService.GetSection:input_type -> section.GetSectionRequest
	4,  // 8: section.SectionService.CreateSection:output_type -> section.CreateSectionResponse
	6,  // 9: section.SectionService.UpdateSection:output_type -> section.UpdateSectionResponse
	8,  // 10: section.SectionService.DeleteSection:output_type -> section.DeleteSectionResponse
	9,  // 11: section.SectionService.ListSections:output_type -> section.SectionListResponse
	2,  // 12: section.SectionService.GetSection:output_type -> section.SectionResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_section_proto_init() }
func file_section_proto_init() {
	if File_section_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_section_proto_rawDesc), len(file_section_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_section_proto_goTypes,
		DependencyIndexes: file_section_proto_depIdxs,
		MessageInfos:      file_section_proto_msgTypes,
	}.Build()
	File_section_proto = out.File
	file_section_proto_goTypes = nil
	file_section_proto_depIdxs = nil
}
