// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: post.proto

package server

import (
	"context"

	"temp/common/proto"
	"temp/post/rpc/internal/logic"
	"temp/post/rpc/internal/svc"
	"temp/post/rpc/post"
)

type PostServiceServer struct {
	svcCtx *svc.ServiceContext
	post.UnimplementedPostServiceServer
}

func NewPostServiceServer(svcCtx *svc.ServiceContext) *PostServiceServer {
	return &PostServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServiceServer) CreatePost(ctx context.Context, in *post.PostRequest) (*post.PostResp, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *PostServiceServer) GetPost(ctx context.Context, in *post.IdPathReq) (*post.PostResp, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

func (s *PostServiceServer) UpdatePost(ctx context.Context, in *post.UpdatePostReq) (*post.PostResp, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *PostServiceServer) DeletePost(ctx context.Context, in *post.IdPathReq) (*post.CommonResp, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *PostServiceServer) PinPost(ctx context.Context, in *post.ToggleReq) (*post.CommonResp, error) {
	l := logic.NewPinPostLogic(ctx, s.svcCtx)
	return l.PinPost(in)
}

func (s *PostServiceServer) FeaturePost(ctx context.Context, in *post.ToggleReq) (*post.CommonResp, error) {
	l := logic.NewFeaturePostLogic(ctx, s.svcCtx)
	return l.FeaturePost(in)
}

func (s *PostServiceServer) ExistsPost(ctx context.Context, in *post.IdPathReq) (*post.ExistsResp, error) {
	l := logic.NewExistsPostLogic(ctx, s.svcCtx)
	return l.ExistsPost(in)
}

func (s *PostServiceServer) MetaPost(ctx context.Context, in *post.IdPathReq) (*post.PostMetaResp, error) {
	l := logic.NewMetaPostLogic(ctx, s.svcCtx)
	return l.MetaPost(in)
}

func (s *PostServiceServer) Search(ctx context.Context, in *proto.SearchRequest) (*proto.SearchResponse, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}
