// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: file.proto

package fileservice

import (
	"context"

	"temp/file/rpc/file"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConfirmAvatarUploadRequest    = file.ConfirmAvatarUploadRequest
	ConfirmPostImageUploadRequest = file.ConfirmPostImageUploadRequest
	ConfirmUploadRequest          = file.ConfirmUploadRequest
	ConfirmUploadResponse         = file.ConfirmUploadResponse
	GetAvatarRequest              = file.GetAvatarRequest
	GetAvatarUploadRequest        = file.GetAvatarUploadRequest
	GetFileRequest                = file.GetFileRequest
	GetPostImageUploadRequest     = file.GetPostImageUploadRequest
	GetPostImagesRequest          = file.GetPostImagesRequest
	GetPostImagesResponse         = file.GetPostImagesResponse
	GetUploadURLRequest           = file.GetUploadURLRequest
	UploadURLResponse             = file.UploadURLResponse
	UrlResponse                   = file.UrlResponse

	FileService interface {
		// 生成上传凭证（需要鉴权）
		GetUploadURL(ctx context.Context, in *GetUploadURLRequest, opts ...grpc.CallOption) (*UploadURLResponse, error)
		// 生成上传头像的上传凭证（为当前用户）
		GetAvatarUploadURL(ctx context.Context, in *GetAvatarUploadRequest, opts ...grpc.CallOption) (*UploadURLResponse, error)
		// 生成上传帖子图片的上传凭证（需要指定 post_id）
		GetPostImageUploadURL(ctx context.Context, in *GetPostImageUploadRequest, opts ...grpc.CallOption) (*UploadURLResponse, error)
		// 确认上传完成（保存记录到数据库）
		ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error)
		// 确认头像上传完成
		ConfirmAvatarUpload(ctx context.Context, in *ConfirmAvatarUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error)
		// 确认帖子图片上传完成
		ConfirmPostImageUpload(ctx context.Context, in *ConfirmPostImageUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error)
		// 获取文件信息
		GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*UrlResponse, error)
		// 获取用户头像
		GetAvatar(ctx context.Context, in *GetAvatarRequest, opts ...grpc.CallOption) (*UrlResponse, error)
		// 获取某帖的图片列表
		GetPostImages(ctx context.Context, in *GetPostImagesRequest, opts ...grpc.CallOption) (*GetPostImagesResponse, error)
	}

	defaultFileService struct {
		cli zrpc.Client
	}
)

func NewFileService(cli zrpc.Client) FileService {
	return &defaultFileService{
		cli: cli,
	}
}

// 生成上传凭证（需要鉴权）
func (m *defaultFileService) GetUploadURL(ctx context.Context, in *GetUploadURLRequest, opts ...grpc.CallOption) (*UploadURLResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.GetUploadURL(ctx, in, opts...)
}

// 生成上传头像的上传凭证（为当前用户）
func (m *defaultFileService) GetAvatarUploadURL(ctx context.Context, in *GetAvatarUploadRequest, opts ...grpc.CallOption) (*UploadURLResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.GetAvatarUploadURL(ctx, in, opts...)
}

// 生成上传帖子图片的上传凭证（需要指定 post_id）
func (m *defaultFileService) GetPostImageUploadURL(ctx context.Context, in *GetPostImageUploadRequest, opts ...grpc.CallOption) (*UploadURLResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.GetPostImageUploadURL(ctx, in, opts...)
}

// 确认上传完成（保存记录到数据库）
func (m *defaultFileService) ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.ConfirmUpload(ctx, in, opts...)
}

// 确认头像上传完成
func (m *defaultFileService) ConfirmAvatarUpload(ctx context.Context, in *ConfirmAvatarUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.ConfirmAvatarUpload(ctx, in, opts...)
}

// 确认帖子图片上传完成
func (m *defaultFileService) ConfirmPostImageUpload(ctx context.Context, in *ConfirmPostImageUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.ConfirmPostImageUpload(ctx, in, opts...)
}

// 获取文件信息
func (m *defaultFileService) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*UrlResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.GetFile(ctx, in, opts...)
}

// 获取用户头像
func (m *defaultFileService) GetAvatar(ctx context.Context, in *GetAvatarRequest, opts ...grpc.CallOption) (*UrlResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.GetAvatar(ctx, in, opts...)
}

// 获取某帖的图片列表
func (m *defaultFileService) GetPostImages(ctx context.Context, in *GetPostImagesRequest, opts ...grpc.CallOption) (*GetPostImagesResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.GetPostImages(ctx, in, opts...)
}
