apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: temp
  labels:
    app: auth
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: temp-auth:latest
        ports:
        - containerPort: 8001
        readinessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: temp
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: auth

---


