// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: comment.proto

package commentservice

import (
	"context"

	"temp/comment/rpc/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentResp         = comment.CommentResp
	CreateCommentReq    = comment.CreateCommentReq
	DeleteCommentReq    = comment.DeleteCommentReq
	DeleteCommentResp   = comment.DeleteCommentResp
	GetCommentCountReq  = comment.GetCommentCountReq
	GetCommentCountResp = comment.GetCommentCountResp
	ListCommentsReq     = comment.ListCommentsReq
	ListCommentsResp    = comment.ListCommentsResp

	CommentService interface {
		// 创建评论
		CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CommentResp, error)
		// 获取帖子评论列表
		ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error)
		// 删除评论
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
		// 获取帖子评论数
		GetCommentCount(ctx context.Context, in *GetCommentCountReq, opts ...grpc.CallOption) (*GetCommentCountResp, error)
	}

	defaultCommentService struct {
		cli zrpc.Client
	}
)

func NewCommentService(cli zrpc.Client) CommentService {
	return &defaultCommentService{
		cli: cli,
	}
}

// 创建评论
func (m *defaultCommentService) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CommentResp, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

// 获取帖子评论列表
func (m *defaultCommentService) ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.ListComments(ctx, in, opts...)
}

// 删除评论
func (m *defaultCommentService) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

// 获取帖子评论数
func (m *defaultCommentService) GetCommentCount(ctx context.Context, in *GetCommentCountReq, opts ...grpc.CallOption) (*GetCommentCountResp, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.GetCommentCount(ctx, in, opts...)
}
