// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interaction.proto

package interactionclient

import (
	"context"

	"temp/interaction/rpc/interaction"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp                    = interaction.CommonResp
	FavoriteRequest               = interaction.FavoriteRequest
	FollowRequest                 = interaction.FollowRequest
	GetMyFavouritesRequest        = interaction.GetMyFavouritesRequest
	GetMyFavouritesResponse       = interaction.GetMyFavouritesResponse
	GetMyFollowingRequest         = interaction.GetMyFollowingRequest
	GetMyFollowingResponse        = interaction.GetMyFollowingResponse
	GetPostFavoritesCountRequest  = interaction.GetPostFavoritesCountRequest
	GetPostFavoritesCountResponse = interaction.GetPostFavoritesCountResponse
	LikeRequest                   = interaction.LikeRequest
	PostId                        = interaction.PostId
	UserId                        = interaction.UserId

	Interaction interface {
		Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*CommonResp, error)
		Favorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*CommonResp, error)
		Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*CommonResp, error)
		GetMyFollowing(ctx context.Context, in *GetMyFollowingRequest, opts ...grpc.CallOption) (*GetMyFollowingResponse, error)
		GetMyFavourites(ctx context.Context, in *GetMyFavouritesRequest, opts ...grpc.CallOption) (*GetMyFavouritesResponse, error)
		GetPostFavoritesCount(ctx context.Context, in *GetPostFavoritesCountRequest, opts ...grpc.CallOption) (*GetPostFavoritesCountResponse, error)
	}

	defaultInteraction struct {
		cli zrpc.Client
	}
)

func NewInteraction(cli zrpc.Client) Interaction {
	return &defaultInteraction{
		cli: cli,
	}
}

func (m *defaultInteraction) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*CommonResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

func (m *defaultInteraction) Favorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*CommonResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.Favorite(ctx, in, opts...)
}

func (m *defaultInteraction) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*CommonResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultInteraction) GetMyFollowing(ctx context.Context, in *GetMyFollowingRequest, opts ...grpc.CallOption) (*GetMyFollowingResponse, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetMyFollowing(ctx, in, opts...)
}

func (m *defaultInteraction) GetMyFavourites(ctx context.Context, in *GetMyFavouritesRequest, opts ...grpc.CallOption) (*GetMyFavouritesResponse, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetMyFavourites(ctx, in, opts...)
}

func (m *defaultInteraction) GetPostFavoritesCount(ctx context.Context, in *GetPostFavoritesCountRequest, opts ...grpc.CallOption) (*GetPostFavoritesCountResponse, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetPostFavoritesCount(ctx, in, opts...)
}
