// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: interaction.proto

package interaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Interaction_Like_FullMethodName                  = "/interaction.Interaction/Like"
	Interaction_Favorite_FullMethodName              = "/interaction.Interaction/Favorite"
	Interaction_Follow_FullMethodName                = "/interaction.Interaction/Follow"
	Interaction_GetMyFollowing_FullMethodName        = "/interaction.Interaction/GetMyFollowing"
	Interaction_GetMyFavourites_FullMethodName       = "/interaction.Interaction/GetMyFavourites"
	Interaction_GetPostFavoritesCount_FullMethodName = "/interaction.Interaction/GetPostFavoritesCount"
)

// InteractionClient is the client API for Interaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionClient interface {
	Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*CommonResp, error)
	Favorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*CommonResp, error)
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*CommonResp, error)
	GetMyFollowing(ctx context.Context, in *GetMyFollowingRequest, opts ...grpc.CallOption) (*GetMyFollowingResponse, error)
	GetMyFavourites(ctx context.Context, in *GetMyFavouritesRequest, opts ...grpc.CallOption) (*GetMyFavouritesResponse, error)
	GetPostFavoritesCount(ctx context.Context, in *GetPostFavoritesCountRequest, opts ...grpc.CallOption) (*GetPostFavoritesCountResponse, error)
}

type interactionClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionClient(cc grpc.ClientConnInterface) InteractionClient {
	return &interactionClient{cc}
}

func (c *interactionClient) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Interaction_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) Favorite(ctx context.Context, in *FavoriteRequest, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Interaction_Favorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*CommonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, Interaction_Follow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) GetMyFollowing(ctx context.Context, in *GetMyFollowingRequest, opts ...grpc.CallOption) (*GetMyFollowingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyFollowingResponse)
	err := c.cc.Invoke(ctx, Interaction_GetMyFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) GetMyFavourites(ctx context.Context, in *GetMyFavouritesRequest, opts ...grpc.CallOption) (*GetMyFavouritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyFavouritesResponse)
	err := c.cc.Invoke(ctx, Interaction_GetMyFavourites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) GetPostFavoritesCount(ctx context.Context, in *GetPostFavoritesCountRequest, opts ...grpc.CallOption) (*GetPostFavoritesCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostFavoritesCountResponse)
	err := c.cc.Invoke(ctx, Interaction_GetPostFavoritesCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServer is the server API for Interaction service.
// All implementations must embed UnimplementedInteractionServer
// for forward compatibility.
type InteractionServer interface {
	Like(context.Context, *LikeRequest) (*CommonResp, error)
	Favorite(context.Context, *FavoriteRequest) (*CommonResp, error)
	Follow(context.Context, *FollowRequest) (*CommonResp, error)
	GetMyFollowing(context.Context, *GetMyFollowingRequest) (*GetMyFollowingResponse, error)
	GetMyFavourites(context.Context, *GetMyFavouritesRequest) (*GetMyFavouritesResponse, error)
	GetPostFavoritesCount(context.Context, *GetPostFavoritesCountRequest) (*GetPostFavoritesCountResponse, error)
	mustEmbedUnimplementedInteractionServer()
}

// UnimplementedInteractionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionServer struct{}

func (UnimplementedInteractionServer) Like(context.Context, *LikeRequest) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedInteractionServer) Favorite(context.Context, *FavoriteRequest) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Favorite not implemented")
}
func (UnimplementedInteractionServer) Follow(context.Context, *FollowRequest) (*CommonResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedInteractionServer) GetMyFollowing(context.Context, *GetMyFollowingRequest) (*GetMyFollowingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyFollowing not implemented")
}
func (UnimplementedInteractionServer) GetMyFavourites(context.Context, *GetMyFavouritesRequest) (*GetMyFavouritesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyFavourites not implemented")
}
func (UnimplementedInteractionServer) GetPostFavoritesCount(context.Context, *GetPostFavoritesCountRequest) (*GetPostFavoritesCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostFavoritesCount not implemented")
}
func (UnimplementedInteractionServer) mustEmbedUnimplementedInteractionServer() {}
func (UnimplementedInteractionServer) testEmbeddedByValue()                     {}

// UnsafeInteractionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServer will
// result in compilation errors.
type UnsafeInteractionServer interface {
	mustEmbedUnimplementedInteractionServer()
}

func RegisterInteractionServer(s grpc.ServiceRegistrar, srv InteractionServer) {
	// If the following call panics, it indicates UnimplementedInteractionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Interaction_ServiceDesc, srv)
}

func _Interaction_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).Like(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_Favorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).Favorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_Favorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).Favorite(ctx, req.(*FavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_Follow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_GetMyFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).GetMyFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_GetMyFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).GetMyFollowing(ctx, req.(*GetMyFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_GetMyFavourites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyFavouritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).GetMyFavourites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_GetMyFavourites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).GetMyFavourites(ctx, req.(*GetMyFavouritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_GetPostFavoritesCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostFavoritesCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).GetPostFavoritesCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_GetPostFavoritesCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).GetPostFavoritesCount(ctx, req.(*GetPostFavoritesCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Interaction_ServiceDesc is the grpc.ServiceDesc for Interaction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Interaction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.Interaction",
	HandlerType: (*InteractionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Like",
			Handler:    _Interaction_Like_Handler,
		},
		{
			MethodName: "Favorite",
			Handler:    _Interaction_Favorite_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _Interaction_Follow_Handler,
		},
		{
			MethodName: "GetMyFollowing",
			Handler:    _Interaction_GetMyFollowing_Handler,
		},
		{
			MethodName: "GetMyFavourites",
			Handler:    _Interaction_GetMyFavourites_Handler,
		},
		{
			MethodName: "GetPostFavoritesCount",
			Handler:    _Interaction_GetPostFavoritesCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}
