// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: interaction.proto

package interaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Like          bool                   `protobuf:"varint,3,opt,name=like,proto3" json:"like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *LikeRequest) GetLike() bool {
	if x != nil {
		return x.Like
	}
	return false
}

type FavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Favorite      bool                   `protobuf:"varint,3,opt,name=favorite,proto3" json:"favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteRequest) Reset() {
	*x = FavoriteRequest{}
	mi := &file_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteRequest) ProtoMessage() {}

func (x *FavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteRequest.ProtoReflect.Descriptor instead.
func (*FavoriteRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *FavoriteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FavoriteRequest) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   int64                  `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *FollowRequest) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *FollowRequest) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

func (x *FollowRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type GetMyFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyFollowingRequest) Reset() {
	*x = GetMyFollowingRequest{}
	mi := &file_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFollowingRequest) ProtoMessage() {}

func (x *GetMyFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetMyFollowingRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyFollowingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMyFollowingRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyFollowingRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMyFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     []*UserId              `protobuf:"bytes,1,rep,name=following,proto3" json:"following,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyFollowingResponse) Reset() {
	*x = GetMyFollowingResponse{}
	mi := &file_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFollowingResponse) ProtoMessage() {}

func (x *GetMyFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetMyFollowingResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyFollowingResponse) GetFollowing() []*UserId {
	if x != nil {
		return x.Following
	}
	return nil
}

func (x *GetMyFollowingResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetMyFavouritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyFavouritesRequest) Reset() {
	*x = GetMyFavouritesRequest{}
	mi := &file_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyFavouritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFavouritesRequest) ProtoMessage() {}

func (x *GetMyFavouritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFavouritesRequest.ProtoReflect.Descriptor instead.
func (*GetMyFavouritesRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *GetMyFavouritesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMyFavouritesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyFavouritesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMyFavouritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favourites    []*PostId              `protobuf:"bytes,1,rep,name=favourites,proto3" json:"favourites,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyFavouritesResponse) Reset() {
	*x = GetMyFavouritesResponse{}
	mi := &file_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyFavouritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFavouritesResponse) ProtoMessage() {}

func (x *GetMyFavouritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFavouritesResponse.ProtoReflect.Descriptor instead.
func (*GetMyFavouritesResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *GetMyFavouritesResponse) GetFavourites() []*PostId {
	if x != nil {
		return x.Favourites
	}
	return nil
}

func (x *GetMyFavouritesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPostFavoritesCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostFavoritesCountRequest) Reset() {
	*x = GetPostFavoritesCountRequest{}
	mi := &file_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostFavoritesCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostFavoritesCountRequest) ProtoMessage() {}

func (x *GetPostFavoritesCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostFavoritesCountRequest.ProtoReflect.Descriptor instead.
func (*GetPostFavoritesCountRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostFavoritesCountRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostFavoritesCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostFavoritesCountResponse) Reset() {
	*x = GetPostFavoritesCountResponse{}
	mi := &file_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostFavoritesCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostFavoritesCountResponse) ProtoMessage() {}

func (x *GetPostFavoritesCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostFavoritesCountResponse.ProtoReflect.Descriptor instead.
func (*GetPostFavoritesCountResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *GetPostFavoritesCountResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *UserId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PostId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostId) Reset() {
	*x = PostId{}
	mi := &file_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostId) ProtoMessage() {}

func (x *PostId) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostId.ProtoReflect.Descriptor instead.
func (*PostId) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *PostId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_interaction_proto protoreflect.FileDescriptor

const file_interaction_proto_rawDesc = "" +
	"\n" +
	"\x11interaction.proto\x12\vinteraction\"S\n" +
	"\vLikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x12\n" +
	"\x04like\x18\x03 \x01(\bR\x04like\"_\n" +
	"\x0fFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x1a\n" +
	"\bfavorite\x18\x03 \x01(\bR\bfavorite\"k\n" +
	"\rFollowRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x03R\vfollowingId\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\"a\n" +
	"\x15GetMyFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"a\n" +
	"\x16GetMyFollowingResponse\x121\n" +
	"\tfollowing\x18\x01 \x03(\v2\x13.interaction.UserIdR\tfollowing\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"b\n" +
	"\x16GetMyFavouritesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"d\n" +
	"\x17GetMyFavouritesResponse\x123\n" +
	"\n" +
	"favourites\x18\x01 \x03(\v2\x13.interaction.PostIdR\n" +
	"favourites\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"7\n" +
	"\x1cGetPostFavoritesCountRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"5\n" +
	"\x1dGetPostFavoritesCountResponse\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x18\n" +
	"\x06UserId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x18\n" +
	"\x06PostId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"&\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf3\x03\n" +
	"\vInteraction\x129\n" +
	"\x04Like\x12\x18.interaction.LikeRequest\x1a\x17.interaction.CommonResp\x12A\n" +
	"\bFavorite\x12\x1c.interaction.FavoriteRequest\x1a\x17.interaction.CommonResp\x12=\n" +
	"\x06Follow\x12\x1a.interaction.FollowRequest\x1a\x17.interaction.CommonResp\x12Y\n" +
	"\x0eGetMyFollowing\x12\".interaction.GetMyFollowingRequest\x1a#.interaction.GetMyFollowingResponse\x12\\\n" +
	"\x0fGetMyFavourites\x12#.interaction.GetMyFavouritesRequest\x1a$.interaction.GetMyFavouritesResponse\x12n\n" +
	"\x15GetPostFavoritesCount\x12).interaction.GetPostFavoritesCountRequest\x1a*.interaction.GetPostFavoritesCountResponseB\x0fZ\r./interactionb\x06proto3"

var (
	file_interaction_proto_rawDescOnce sync.Once
	file_interaction_proto_rawDescData []byte
)

func file_interaction_proto_rawDescGZIP() []byte {
	file_interaction_proto_rawDescOnce.Do(func() {
		file_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)))
	})
	return file_interaction_proto_rawDescData
}

var file_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_interaction_proto_goTypes = []any{
	(*LikeRequest)(nil),                   // 0: interaction.LikeRequest
	(*FavoriteRequest)(nil),               // 1: interaction.FavoriteRequest
	(*FollowRequest)(nil),                 // 2: interaction.FollowRequest
	(*GetMyFollowingRequest)(nil),         // 3: interaction.GetMyFollowingRequest
	(*GetMyFollowingResponse)(nil),        // 4: interaction.GetMyFollowingResponse
	(*GetMyFavouritesRequest)(nil),        // 5: interaction.GetMyFavouritesRequest
	(*GetMyFavouritesResponse)(nil),       // 6: interaction.GetMyFavouritesResponse
	(*GetPostFavoritesCountRequest)(nil),  // 7: interaction.GetPostFavoritesCountRequest
	(*GetPostFavoritesCountResponse)(nil), // 8: interaction.GetPostFavoritesCountResponse
	(*UserId)(nil),                        // 9: interaction.UserId
	(*PostId)(nil),                        // 10: interaction.PostId
	(*CommonResp)(nil),                    // 11: interaction.CommonResp
}
var file_interaction_proto_depIdxs = []int32{
	9,  // 0: interaction.GetMyFollowingResponse.following:type_name -> interaction.UserId
	10, // 1: interaction.GetMyFavouritesResponse.favourites:type_name -> interaction.PostId
	0,  // 2: interaction.Interaction.Like:input_type -> interaction.LikeRequest
	1,  // 3: interaction.Interaction.Favorite:input_type -> interaction.FavoriteRequest
	2,  // 4: interaction.Interaction.Follow:input_type -> interaction.FollowRequest
	3,  // 5: interaction.Interaction.GetMyFollowing:input_type -> interaction.GetMyFollowingRequest
	5,  // 6: interaction.Interaction.GetMyFavourites:input_type -> interaction.GetMyFavouritesRequest
	7,  // 7: interaction.Interaction.GetPostFavoritesCount:input_type -> interaction.GetPostFavoritesCountRequest
	11, // 8: interaction.Interaction.Like:output_type -> interaction.CommonResp
	11, // 9: interaction.Interaction.Favorite:output_type -> interaction.CommonResp
	11, // 10: interaction.Interaction.Follow:output_type -> interaction.CommonResp
	4,  // 11: interaction.Interaction.GetMyFollowing:output_type -> interaction.GetMyFollowingResponse
	6,  // 12: interaction.Interaction.GetMyFavourites:output_type -> interaction.GetMyFavouritesResponse
	8,  // 13: interaction.Interaction.GetPostFavoritesCount:output_type -> interaction.GetPostFavoritesCountResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_interaction_proto_init() }
func file_interaction_proto_init() {
	if File_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interaction_proto_goTypes,
		DependencyIndexes: file_interaction_proto_depIdxs,
		MessageInfos:      file_interaction_proto_msgTypes,
	}.Build()
	File_interaction_proto = out.File
	file_interaction_proto_goTypes = nil
	file_interaction_proto_depIdxs = nil
}
