// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: post.proto

package postservice

import (
	"context"

	"temp/post/rpc/post"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp    = post.CommonResp
	ExistsResp    = post.ExistsResp
	IdPathReq     = post.IdPathReq
	PostMetaResp  = post.PostMetaResp
	PostRequest   = post.PostRequest
	PostResp      = post.PostResp
	ToggleReq     = post.ToggleReq
	UpdatePostReq = post.UpdatePostReq

	PostService interface {
		CreatePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResp, error)
		GetPost(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*PostResp, error)
		UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*PostResp, error)
		DeletePost(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*CommonResp, error)
		PinPost(ctx context.Context, in *ToggleReq, opts ...grpc.CallOption) (*CommonResp, error)
		FeaturePost(ctx context.Context, in *ToggleReq, opts ...grpc.CallOption) (*CommonResp, error)
		ExistsPost(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*ExistsResp, error)
		MetaPost(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*PostMetaResp, error)
	}

	defaultPostService struct {
		cli zrpc.Client
	}
)

func NewPostService(cli zrpc.Client) PostService {
	return &defaultPostService{
		cli: cli,
	}
}

func (m *defaultPostService) CreatePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

func (m *defaultPostService) GetPost(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*PostResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.GetPost(ctx, in, opts...)
}

func (m *defaultPostService) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*PostResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

func (m *defaultPostService) DeletePost(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

func (m *defaultPostService) PinPost(ctx context.Context, in *ToggleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.PinPost(ctx, in, opts...)
}

func (m *defaultPostService) FeaturePost(ctx context.Context, in *ToggleReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.FeaturePost(ctx, in, opts...)
}

func (m *defaultPostService) ExistsPost(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*ExistsResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.ExistsPost(ctx, in, opts...)
}

func (m *defaultPostService) MetaPost(ctx context.Context, in *IdPathReq, opts ...grpc.CallOption) (*PostMetaResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.MetaPost(ctx, in, opts...)
}
