// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package server

import (
	"context"

	"temp/common/proto"
	"temp/search/rpc/internal/logic"
	"temp/search/rpc/internal/svc"
	"temp/search/rpc/search"
)

type SearchServiceServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServiceServer
}

func NewSearchServiceServer(svcCtx *svc.ServiceContext) *SearchServiceServer {
	return &SearchServiceServer{
		svcCtx: svcCtx,
	}
}

// 分页搜索
func (s *SearchServiceServer) Search(ctx context.Context, in *proto.SearchRequest) (*proto.SearchResponse, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}
