// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"temp/user/internal/logic"
	"temp/user/internal/svc"
	"temp/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserServer) GetUserInfoBy(ctx context.Context, in *user.GetUserInfoRequest) (*user.UserInfoResponse, error) {
	l := logic.NewGetUserInfoByLogic(ctx, s.svcCtx)
	return l.GetUserInfoBy(in)
}

func (s *UserServer) UpdateUserInfo(ctx context.Context, in *user.GetUserInfoRequest) (*user.UserInfoResponse, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}
