// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: section.proto

package server

import (
	"context"

	"temp/section/rpc/internal/logic"
	"temp/section/rpc/internal/svc"
	"temp/section/rpc/section/rpc"
)

type SectionServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedSectionServiceServer
}

func NewSectionServiceServer(svcCtx *svc.ServiceContext) *SectionServiceServer {
	return &SectionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SectionServiceServer) CreateSection(ctx context.Context, in *rpc.CreateSectionRequest) (*rpc.CreateSectionResponse, error) {
	l := logic.NewCreateSectionLogic(ctx, s.svcCtx)
	return l.CreateSection(in)
}

func (s *SectionServiceServer) UpdateSection(ctx context.Context, in *rpc.UpdateSectionRequest) (*rpc.UpdateSectionResponse, error) {
	l := logic.NewUpdateSectionLogic(ctx, s.svcCtx)
	return l.UpdateSection(in)
}

func (s *SectionServiceServer) DeleteSection(ctx context.Context, in *rpc.DeleteSectionRequest) (*rpc.DeleteSectionResponse, error) {
	l := logic.NewDeleteSectionLogic(ctx, s.svcCtx)
	return l.DeleteSection(in)
}

func (s *SectionServiceServer) ListSections(ctx context.Context, in *rpc.Empty) (*rpc.SectionListResponse, error) {
	l := logic.NewListSectionsLogic(ctx, s.svcCtx)
	return l.ListSections(in)
}

func (s *SectionServiceServer) GetSection(ctx context.Context, in *rpc.GetSectionRequest) (*rpc.SectionResponse, error) {
	l := logic.NewGetSectionLogic(ctx, s.svcCtx)
	return l.GetSection(in)
}
