// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package searchservice

import (
	"context"

	"temp/search/rpc/search"

	"temp/common/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SearchService interface {
		// 分页搜索
		Search(ctx context.Context, in *proto.SearchRequest, opts ...grpc.CallOption) (*proto.SearchResponse, error)
	}

	defaultSearchService struct {
		cli zrpc.Client
	}
)

func NewSearchService(cli zrpc.Client) SearchService {
	return &defaultSearchService{
		cli: cli,
	}
}

// 分页搜索
func (m *defaultSearchService) Search(ctx context.Context, in *proto.SearchRequest, opts ...grpc.CallOption) (*proto.SearchResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.Search(ctx, in, opts...)
}
