// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetSectionReq struct {
	Id int64 `path:"id"`
}

type GetSectionResp struct {
	Item Section `json:"section"`
}

type Section struct {
	Id          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	OrderIndex  int    `json:"orderIndex"`
	Visibility  bool   `json:"visibility"`
}

type SectionListResp struct {
	List  []Section `json:"list"`
	Total int64     `json:"total"`
}
