// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: file.proto

package server

import (
	"context"

	"temp/file/rpc/file"
	"temp/file/rpc/internal/logic"
	"temp/file/rpc/internal/svc"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	file.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

// 生成上传凭证（需要鉴权）
func (s *FileServiceServer) GetUploadURL(ctx context.Context, in *file.GetUploadURLRequest) (*file.UploadURLResponse, error) {
	l := logic.NewGetUploadURLLogic(ctx, s.svcCtx)
	return l.GetUploadURL(in)
}

// 生成上传头像的上传凭证（为当前用户）
func (s *FileServiceServer) GetAvatarUploadURL(ctx context.Context, in *file.GetAvatarUploadRequest) (*file.UploadURLResponse, error) {
	l := logic.NewGetAvatarUploadLogic(ctx, s.svcCtx)
	return l.GetAvatarUploadURL(in)
}

// 生成上传帖子图片的上传凭证（需要指定 post_id）
func (s *FileServiceServer) GetPostImageUploadURL(ctx context.Context, in *file.GetPostImageUploadRequest) (*file.UploadURLResponse, error) {
	l := logic.NewGetPostImageUploadLogic(ctx, s.svcCtx)
	return l.GetPostImageUploadURL(in)
}

// 确认上传完成（保存记录到数据库）
func (s *FileServiceServer) ConfirmUpload(ctx context.Context, in *file.ConfirmUploadRequest) (*file.ConfirmUploadResponse, error) {
	l := logic.NewConfirmUploadLogic(ctx, s.svcCtx)
	return l.ConfirmUpload(in)
}

// 确认头像上传完成
func (s *FileServiceServer) ConfirmAvatarUpload(ctx context.Context, in *file.ConfirmAvatarUploadRequest) (*file.ConfirmUploadResponse, error) {
	l := logic.NewConfirmAvatarUploadLogic(ctx, s.svcCtx)
	return l.ConfirmAvatarUpload(in)
}

// 确认帖子图片上传完成
func (s *FileServiceServer) ConfirmPostImageUpload(ctx context.Context, in *file.ConfirmPostImageUploadRequest) (*file.ConfirmUploadResponse, error) {
	l := logic.NewConfirmPostImageUploadLogic(ctx, s.svcCtx)
	return l.ConfirmPostImageUpload(in)
}

// 获取文件信息
func (s *FileServiceServer) GetFile(ctx context.Context, in *file.GetFileRequest) (*file.UrlResponse, error) {
	l := logic.NewGetFileLogic(ctx, s.svcCtx)
	return l.GetFile(in)
}

// 获取用户头像
func (s *FileServiceServer) GetAvatar(ctx context.Context, in *file.GetAvatarRequest) (*file.UrlResponse, error) {
	l := logic.NewGetAvatarLogic(ctx, s.svcCtx)
	return l.GetAvatar(in)
}

// 获取某帖的图片列表
func (s *FileServiceServer) GetPostImages(ctx context.Context, in *file.GetPostImagesRequest) (*file.GetPostImagesResponse, error) {
	l := logic.NewGetPostImagesLogic(ctx, s.svcCtx)
	return l.GetPostImages(in)
}
