// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: comment.proto

package server

import (
	"context"

	"temp/comment/rpc/comment"
	"temp/comment/rpc/internal/logic"
	"temp/comment/rpc/internal/svc"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建评论
func (s *CommentServiceServer) CreateComment(ctx context.Context, in *comment.CreateCommentReq) (*comment.CommentResp, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

// 获取帖子评论列表
func (s *CommentServiceServer) ListComments(ctx context.Context, in *comment.ListCommentsReq) (*comment.ListCommentsResp, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}

// 删除评论
func (s *CommentServiceServer) DeleteComment(ctx context.Context, in *comment.DeleteCommentReq) (*comment.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

// 获取帖子评论数
func (s *CommentServiceServer) GetCommentCount(ctx context.Context, in *comment.GetCommentCountReq) (*comment.GetCommentCountResp, error) {
	l := logic.NewGetCommentCountLogic(ctx, s.svcCtx)
	return l.GetCommentCount(in)
}
