// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommonResp struct {
	Message string `json:"message,optional"`
}

type ExistsResp struct {
	Data bool `json:"data"`
}

type IdPathReq struct {
	Id int64 `path:"id"`
}

type Post struct {
	Id        int64  `json:"id"`
	AuthorId  int64  `json:"authorId"`
	SectionId int64  `json:"sectionId"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	ViewCount int64  `json:"viewCount"`
	Pinned    bool   `json:"pinned"`
	Featured  bool   `json:"featured"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type PostMeta struct {
	Id        int64  `json:"id"`
	AuthorId  int64  `json:"authorId"`
	SectionId int64  `json:"sectionId"`
	Title     string `json:"title"`
}

type PostMetaResp struct {
	Data PostMeta `json:"data"`
}

type PostRequest struct {
	AuthorId  int64  `json:"authorId"`
	SectionId int64  `json:"sectionId"`
	Title     string `json:"title"`
	Content   string `json:"content"`
}

type PostResp struct {
	Data Post `json:"data"`
}

type ToggleReq struct {
	Id    int64 `path:"id"`
	Value bool  `form:"value"`
}

type UpdatePostReq struct {
	Id        int64  `path:"id"`
	AuthorId  int64  `json:"authorId"`
	SectionId int64  `json:"sectionId"`
	Title     string `json:"title"`
	Content   string `json:"content"`
}
