// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: post.proto

package post

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "temp/common/proto"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	SectionId     uint64                 `protobuf:"varint,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *PostRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PostRequest) GetSectionId() uint64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *PostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	SectionId     uint64                 `protobuf:"varint,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ViewCount     int64                  `protobuf:"varint,6,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	Pinned        bool                   `protobuf:"varint,7,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Featured      bool                   `protobuf:"varint,8,opt,name=featured,proto3" json:"featured,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResp) Reset() {
	*x = PostResp{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResp) ProtoMessage() {}

func (x *PostResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResp.ProtoReflect.Descriptor instead.
func (*PostResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *PostResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostResp) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PostResp) GetSectionId() uint64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *PostResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostResp) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *PostResp) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *PostResp) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *PostResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PostResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type PostMetaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	SectionId     uint64                 `protobuf:"varint,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMetaResp) Reset() {
	*x = PostMetaResp{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMetaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMetaResp) ProtoMessage() {}

func (x *PostMetaResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMetaResp.ProtoReflect.Descriptor instead.
func (*PostMetaResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *PostMetaResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostMetaResp) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PostMetaResp) GetSectionId() uint64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *PostMetaResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type IdPathReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdPathReq) Reset() {
	*x = IdPathReq{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdPathReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdPathReq) ProtoMessage() {}

func (x *IdPathReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdPathReq.ProtoReflect.Descriptor instead.
func (*IdPathReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *IdPathReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	SectionId     uint64                 `protobuf:"varint,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostReq) Reset() {
	*x = UpdatePostReq{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostReq) ProtoMessage() {}

func (x *UpdatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostReq.ProtoReflect.Descriptor instead.
func (*UpdatePostReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePostReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *UpdatePostReq) GetSectionId() uint64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *UpdatePostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ToggleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleReq) Reset() {
	*x = ToggleReq{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleReq) ProtoMessage() {}

func (x *ToggleReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleReq.ProtoReflect.Descriptor instead.
func (*ToggleReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

func (x *ToggleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToggleReq) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ExistsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          bool                   `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResp) Reset() {
	*x = ExistsResp{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResp) ProtoMessage() {}

func (x *ExistsResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResp.ProtoReflect.Descriptor instead.
func (*ExistsResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

func (x *ExistsResp) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{7}
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\x04post\x1a\x19common/proto/common.proto\"y\n" +
	"\vPostRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\x04R\tsectionId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\x97\x02\n" +
	"\bPostResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\x04R\tsectionId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"view_count\x18\x06 \x01(\x03R\tviewCount\x12\x16\n" +
	"\x06pinned\x18\a \x01(\bR\x06pinned\x12\x1a\n" +
	"\bfeatured\x18\b \x01(\bR\bfeatured\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"p\n" +
	"\fPostMetaResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\x04R\tsectionId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\x1b\n" +
	"\tIdPathReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8b\x01\n" +
	"\rUpdatePostReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\x04R\tsectionId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"1\n" +
	"\tToggleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\" \n" +
	"\n" +
	"ExistsResp\x12\x12\n" +
	"\x04data\x18\x01 \x01(\bR\x04data\"&\n" +
	"\n" +
	"CommonResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc9\x03\n" +
	"\vPostService\x12/\n" +
	"\n" +
	"CreatePost\x12\x11.post.PostRequest\x1a\x0e.post.PostResp\x12*\n" +
	"\aGetPost\x12\x0f.post.IdPathReq\x1a\x0e.post.PostResp\x121\n" +
	"\n" +
	"UpdatePost\x12\x13.post.UpdatePostReq\x1a\x0e.post.PostResp\x12/\n" +
	"\n" +
	"DeletePost\x12\x0f.post.IdPathReq\x1a\x10.post.CommonResp\x12,\n" +
	"\aPinPost\x12\x0f.post.ToggleReq\x1a\x10.post.CommonResp\x120\n" +
	"\vFeaturePost\x12\x0f.post.ToggleReq\x1a\x10.post.CommonResp\x12/\n" +
	"\n" +
	"ExistsPost\x12\x0f.post.IdPathReq\x1a\x10.post.ExistsResp\x12/\n" +
	"\bMetaPost\x12\x0f.post.IdPathReq\x1a\x12.post.PostMetaResp\x127\n" +
	"\x06Search\x12\x15.common.SearchRequest\x1a\x16.common.SearchResponseB\bZ\x06./postb\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_post_proto_goTypes = []any{
	(*PostRequest)(nil),           // 0: post.PostRequest
	(*PostResp)(nil),              // 1: post.PostResp
	(*PostMetaResp)(nil),          // 2: post.PostMetaResp
	(*IdPathReq)(nil),             // 3: post.IdPathReq
	(*UpdatePostReq)(nil),         // 4: post.UpdatePostReq
	(*ToggleReq)(nil),             // 5: post.ToggleReq
	(*ExistsResp)(nil),            // 6: post.ExistsResp
	(*CommonResp)(nil),            // 7: post.CommonResp
	(*common.SearchRequest)(nil),  // 8: common.SearchRequest
	(*common.SearchResponse)(nil), // 9: common.SearchResponse
}
var file_post_proto_depIdxs = []int32{
	0, // 0: post.PostService.CreatePost:input_type -> post.PostRequest
	3, // 1: post.PostService.GetPost:input_type -> post.IdPathReq
	4, // 2: post.PostService.UpdatePost:input_type -> post.UpdatePostReq
	3, // 3: post.PostService.DeletePost:input_type -> post.IdPathReq
	5, // 4: post.PostService.PinPost:input_type -> post.ToggleReq
	5, // 5: post.PostService.FeaturePost:input_type -> post.ToggleReq
	3, // 6: post.PostService.ExistsPost:input_type -> post.IdPathReq
	3, // 7: post.PostService.MetaPost:input_type -> post.IdPathReq
	8, // 8: post.PostService.Search:input_type -> common.SearchRequest
	1, // 9: post.PostService.CreatePost:output_type -> post.PostResp
	1, // 10: post.PostService.GetPost:output_type -> post.PostResp
	1, // 11: post.PostService.UpdatePost:output_type -> post.PostResp
	7, // 12: post.PostService.DeletePost:output_type -> post.CommonResp
	7, // 13: post.PostService.PinPost:output_type -> post.CommonResp
	7, // 14: post.PostService.FeaturePost:output_type -> post.CommonResp
	6, // 15: post.PostService.ExistsPost:output_type -> post.ExistsResp
	2, // 16: post.PostService.MetaPost:output_type -> post.PostMetaResp
	9, // 17: post.PostService.Search:output_type -> common.SearchResponse
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
