// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: file.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求上传凭证
type GetUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`    // 原始文件名
	IsPrivate     bool                   `protobuf:"varint,2,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"` // 是否私有文件
	MimeType      string                 `protobuf:"bytes,3,opt,name=mimeType,proto3" json:"mimeType,omitempty"`    // 文件 MIME 类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLRequest) Reset() {
	*x = GetUploadURLRequest{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLRequest) ProtoMessage() {}

func (x *GetUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *GetUploadURLRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetUploadURLRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *GetUploadURLRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// 上传凭证响应
type UploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=uploadUrl,proto3" json:"uploadUrl,omitempty"`     // 预签名上传 URL
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"` // 下载 URL
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=objectKey,proto3" json:"objectKey,omitempty"`     // OSS 对象键
	ExpiresIn     int32                  `protobuf:"varint,4,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`    // 过期时间（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadURLResponse) Reset() {
	*x = UploadURLResponse{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadURLResponse) ProtoMessage() {}

func (x *UploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadURLResponse.ProtoReflect.Descriptor instead.
func (*UploadURLResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *UploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *UploadURLResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UploadURLResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *UploadURLResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 确认上传完成
type ConfirmUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"` // OSS 对象键
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`   // 原始文件名
	FileSize      int64                  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`  // 文件大小（字节）
	MimeType      string                 `protobuf:"bytes,4,opt,name=mimeType,proto3" json:"mimeType,omitempty"`   // MIME 类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmUploadRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ConfirmUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConfirmUploadRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ConfirmUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// 确认上传响应
type ConfirmUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`     // 文件记录 ID
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`           // 访问 URL
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"` // 文件名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadResponse) Reset() {
	*x = ConfirmUploadResponse{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadResponse) ProtoMessage() {}

func (x *ConfirmUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUploadResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmUploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ConfirmUploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ConfirmUploadResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// 获取文件请求
type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// URL 响应
type UrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlResponse) Reset() {
	*x = UrlResponse{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlResponse) ProtoMessage() {}

func (x *UrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlResponse.ProtoReflect.Descriptor instead.
func (*UrlResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *UrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetAvatarUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,2,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvatarUploadRequest) Reset() {
	*x = GetAvatarUploadRequest{}
	mi := &file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvatarUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarUploadRequest) ProtoMessage() {}

func (x *GetAvatarUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarUploadRequest.ProtoReflect.Descriptor instead.
func (*GetAvatarUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvatarUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetAvatarUploadRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *GetAvatarUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type GetPostImageUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,2,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	PostId        int64                  `protobuf:"varint,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostImageUploadRequest) Reset() {
	*x = GetPostImageUploadRequest{}
	mi := &file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostImageUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostImageUploadRequest) ProtoMessage() {}

func (x *GetPostImageUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostImageUploadRequest.ProtoReflect.Descriptor instead.
func (*GetPostImageUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostImageUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetPostImageUploadRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *GetPostImageUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetPostImageUploadRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type ConfirmAvatarUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmAvatarUploadRequest) Reset() {
	*x = ConfirmAvatarUploadRequest{}
	mi := &file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmAvatarUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmAvatarUploadRequest) ProtoMessage() {}

func (x *ConfirmAvatarUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmAvatarUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmAvatarUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmAvatarUploadRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ConfirmAvatarUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConfirmAvatarUploadRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ConfirmAvatarUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type ConfirmPostImageUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	PostId        int64                  `protobuf:"varint,5,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPostImageUploadRequest) Reset() {
	*x = ConfirmPostImageUploadRequest{}
	mi := &file_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPostImageUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPostImageUploadRequest) ProtoMessage() {}

func (x *ConfirmPostImageUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPostImageUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPostImageUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmPostImageUploadRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ConfirmPostImageUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConfirmPostImageUploadRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ConfirmPostImageUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ConfirmPostImageUploadRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvatarRequest) Reset() {
	*x = GetAvatarRequest{}
	mi := &file_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarRequest) ProtoMessage() {}

func (x *GetAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarRequest.ProtoReflect.Descriptor instead.
func (*GetAvatarRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{10}
}

func (x *GetAvatarRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPostImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostImagesRequest) Reset() {
	*x = GetPostImagesRequest{}
	mi := &file_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostImagesRequest) ProtoMessage() {}

func (x *GetPostImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostImagesRequest.ProtoReflect.Descriptor instead.
func (*GetPostImagesRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{11}
}

func (x *GetPostImagesRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UrlResponse         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostImagesResponse) Reset() {
	*x = GetPostImagesResponse{}
	mi := &file_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostImagesResponse) ProtoMessage() {}

func (x *GetPostImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostImagesResponse.ProtoReflect.Descriptor instead.
func (*GetPostImagesResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{12}
}

func (x *GetPostImagesResponse) GetItems() []*UrlResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\x04file\"k\n" +
	"\x13GetUploadURLRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1c\n" +
	"\tisPrivate\x18\x02 \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bmimeType\x18\x03 \x01(\tR\bmimeType\"\x8f\x01\n" +
	"\x11UploadURLResponse\x12\x1c\n" +
	"\tuploadUrl\x18\x01 \x01(\tR\tuploadUrl\x12 \n" +
	"\vdownloadUrl\x18\x02 \x01(\tR\vdownloadUrl\x12\x1c\n" +
	"\tobjectKey\x18\x03 \x01(\tR\tobjectKey\x12\x1c\n" +
	"\texpiresIn\x18\x04 \x01(\x05R\texpiresIn\"\x88\x01\n" +
	"\x14ConfirmUploadRequest\x12\x1c\n" +
	"\tobjectKey\x18\x01 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfileSize\x18\x03 \x01(\x03R\bfileSize\x12\x1a\n" +
	"\bmimeType\x18\x04 \x01(\tR\bmimeType\"]\n" +
	"\x15ConfirmUploadResponse\x12\x16\n" +
	"\x06fileId\x18\x01 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\" \n" +
	"\x0eGetFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\vUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"n\n" +
	"\x16GetAvatarUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1c\n" +
	"\tisPrivate\x18\x02 \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bmimeType\x18\x03 \x01(\tR\bmimeType\"\x8a\x01\n" +
	"\x19GetPostImageUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1c\n" +
	"\tisPrivate\x18\x02 \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bmimeType\x18\x03 \x01(\tR\bmimeType\x12\x17\n" +
	"\apost_id\x18\x04 \x01(\x03R\x06postId\"\x8e\x01\n" +
	"\x1aConfirmAvatarUploadRequest\x12\x1c\n" +
	"\tobjectKey\x18\x01 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfileSize\x18\x03 \x01(\x03R\bfileSize\x12\x1a\n" +
	"\bmimeType\x18\x04 \x01(\tR\bmimeType\"\xaa\x01\n" +
	"\x1dConfirmPostImageUploadRequest\x12\x1c\n" +
	"\tobjectKey\x18\x01 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfileSize\x18\x03 \x01(\x03R\bfileSize\x12\x1a\n" +
	"\bmimeType\x18\x04 \x01(\tR\bmimeType\x12\x17\n" +
	"\apost_id\x18\x05 \x01(\x03R\x06postId\"+\n" +
	"\x10GetAvatarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"/\n" +
	"\x14GetPostImagesRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"@\n" +
	"\x15GetPostImagesResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.file.UrlResponseR\x05items2\xa3\x05\n" +
	"\vFileService\x12B\n" +
	"\fGetUploadURL\x12\x19.file.GetUploadURLRequest\x1a\x17.file.UploadURLResponse\x12K\n" +
	"\x12GetAvatarUploadURL\x12\x1c.file.GetAvatarUploadRequest\x1a\x17.file.UploadURLResponse\x12Q\n" +
	"\x15GetPostImageUploadURL\x12\x1f.file.GetPostImageUploadRequest\x1a\x17.file.UploadURLResponse\x12H\n" +
	"\rConfirmUpload\x12\x1a.file.ConfirmUploadRequest\x1a\x1b.file.ConfirmUploadResponse\x12T\n" +
	"\x13ConfirmAvatarUpload\x12 .file.ConfirmAvatarUploadRequest\x1a\x1b.file.ConfirmUploadResponse\x12Z\n" +
	"\x16ConfirmPostImageUpload\x12#.file.ConfirmPostImageUploadRequest\x1a\x1b.file.ConfirmUploadResponse\x122\n" +
	"\aGetFile\x12\x14.file.GetFileRequest\x1a\x11.file.UrlResponse\x126\n" +
	"\tGetAvatar\x12\x16.file.GetAvatarRequest\x1a\x11.file.UrlResponse\x12H\n" +
	"\rGetPostImages\x12\x1a.file.GetPostImagesRequest\x1a\x1b.file.GetPostImagesResponseB\bZ\x06./fileb\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_file_proto_goTypes = []any{
	(*GetUploadURLRequest)(nil),           // 0: file.GetUploadURLRequest
	(*UploadURLResponse)(nil),             // 1: file.UploadURLResponse
	(*ConfirmUploadRequest)(nil),          // 2: file.ConfirmUploadRequest
	(*ConfirmUploadResponse)(nil),         // 3: file.ConfirmUploadResponse
	(*GetFileRequest)(nil),                // 4: file.GetFileRequest
	(*UrlResponse)(nil),                   // 5: file.UrlResponse
	(*GetAvatarUploadRequest)(nil),        // 6: file.GetAvatarUploadRequest
	(*GetPostImageUploadRequest)(nil),     // 7: file.GetPostImageUploadRequest
	(*ConfirmAvatarUploadRequest)(nil),    // 8: file.ConfirmAvatarUploadRequest
	(*ConfirmPostImageUploadRequest)(nil), // 9: file.ConfirmPostImageUploadRequest
	(*GetAvatarRequest)(nil),              // 10: file.GetAvatarRequest
	(*GetPostImagesRequest)(nil),          // 11: file.GetPostImagesRequest
	(*GetPostImagesResponse)(nil),         // 12: file.GetPostImagesResponse
}
var file_file_proto_depIdxs = []int32{
	5,  // 0: file.GetPostImagesResponse.items:type_name -> file.UrlResponse
	0,  // 1: file.FileService.GetUploadURL:input_type -> file.GetUploadURLRequest
	6,  // 2: file.FileService.GetAvatarUploadURL:input_type -> file.GetAvatarUploadRequest
	7,  // 3: file.FileService.GetPostImageUploadURL:input_type -> file.GetPostImageUploadRequest
	2,  // 4: file.FileService.ConfirmUpload:input_type -> file.ConfirmUploadRequest
	8,  // 5: file.FileService.ConfirmAvatarUpload:input_type -> file.ConfirmAvatarUploadRequest
	9,  // 6: file.FileService.ConfirmPostImageUpload:input_type -> file.ConfirmPostImageUploadRequest
	4,  // 7: file.FileService.GetFile:input_type -> file.GetFileRequest
	10, // 8: file.FileService.GetAvatar:input_type -> file.GetAvatarRequest
	11, // 9: file.FileService.GetPostImages:input_type -> file.GetPostImagesRequest
	1,  // 10: file.FileService.GetUploadURL:output_type -> file.UploadURLResponse
	1,  // 11: file.FileService.GetAvatarUploadURL:output_type -> file.UploadURLResponse
	1,  // 12: file.FileService.GetPostImageUploadURL:output_type -> file.UploadURLResponse
	3,  // 13: file.FileService.ConfirmUpload:output_type -> file.ConfirmUploadResponse
	3,  // 14: file.FileService.ConfirmAvatarUpload:output_type -> file.ConfirmUploadResponse
	3,  // 15: file.FileService.ConfirmPostImageUpload:output_type -> file.ConfirmUploadResponse
	5,  // 16: file.FileService.GetFile:output_type -> file.UrlResponse
	5,  // 17: file.FileService.GetAvatar:output_type -> file.UrlResponse
	12, // 18: file.FileService.GetPostImages:output_type -> file.GetPostImagesResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
