// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: file.proto

package file

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_GetUploadURL_FullMethodName           = "/file.FileService/GetUploadURL"
	FileService_GetAvatarUploadURL_FullMethodName     = "/file.FileService/GetAvatarUploadURL"
	FileService_GetPostImageUploadURL_FullMethodName  = "/file.FileService/GetPostImageUploadURL"
	FileService_ConfirmUpload_FullMethodName          = "/file.FileService/ConfirmUpload"
	FileService_ConfirmAvatarUpload_FullMethodName    = "/file.FileService/ConfirmAvatarUpload"
	FileService_ConfirmPostImageUpload_FullMethodName = "/file.FileService/ConfirmPostImageUpload"
	FileService_GetFile_FullMethodName                = "/file.FileService/GetFile"
	FileService_GetAvatar_FullMethodName              = "/file.FileService/GetAvatar"
	FileService_GetPostImages_FullMethodName          = "/file.FileService/GetPostImages"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	// 生成上传凭证（需要鉴权）
	GetUploadURL(ctx context.Context, in *GetUploadURLRequest, opts ...grpc.CallOption) (*UploadURLResponse, error)
	// 生成上传头像的上传凭证（为当前用户）
	GetAvatarUploadURL(ctx context.Context, in *GetAvatarUploadRequest, opts ...grpc.CallOption) (*UploadURLResponse, error)
	// 生成上传帖子图片的上传凭证（需要指定 post_id）
	GetPostImageUploadURL(ctx context.Context, in *GetPostImageUploadRequest, opts ...grpc.CallOption) (*UploadURLResponse, error)
	// 确认上传完成（保存记录到数据库）
	ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error)
	// 确认头像上传完成
	ConfirmAvatarUpload(ctx context.Context, in *ConfirmAvatarUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error)
	// 确认帖子图片上传完成
	ConfirmPostImageUpload(ctx context.Context, in *ConfirmPostImageUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error)
	// 获取文件信息
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*UrlResponse, error)
	// 获取用户头像
	GetAvatar(ctx context.Context, in *GetAvatarRequest, opts ...grpc.CallOption) (*UrlResponse, error)
	// 获取某帖的图片列表
	GetPostImages(ctx context.Context, in *GetPostImagesRequest, opts ...grpc.CallOption) (*GetPostImagesResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) GetUploadURL(ctx context.Context, in *GetUploadURLRequest, opts ...grpc.CallOption) (*UploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadURLResponse)
	err := c.cc.Invoke(ctx, FileService_GetUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetAvatarUploadURL(ctx context.Context, in *GetAvatarUploadRequest, opts ...grpc.CallOption) (*UploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadURLResponse)
	err := c.cc.Invoke(ctx, FileService_GetAvatarUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetPostImageUploadURL(ctx context.Context, in *GetPostImageUploadRequest, opts ...grpc.CallOption) (*UploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadURLResponse)
	err := c.cc.Invoke(ctx, FileService_GetPostImageUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmUploadResponse)
	err := c.cc.Invoke(ctx, FileService_ConfirmUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ConfirmAvatarUpload(ctx context.Context, in *ConfirmAvatarUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmUploadResponse)
	err := c.cc.Invoke(ctx, FileService_ConfirmAvatarUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ConfirmPostImageUpload(ctx context.Context, in *ConfirmPostImageUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmUploadResponse)
	err := c.cc.Invoke(ctx, FileService_ConfirmPostImageUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*UrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UrlResponse)
	err := c.cc.Invoke(ctx, FileService_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetAvatar(ctx context.Context, in *GetAvatarRequest, opts ...grpc.CallOption) (*UrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UrlResponse)
	err := c.cc.Invoke(ctx, FileService_GetAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetPostImages(ctx context.Context, in *GetPostImagesRequest, opts ...grpc.CallOption) (*GetPostImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostImagesResponse)
	err := c.cc.Invoke(ctx, FileService_GetPostImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	// 生成上传凭证（需要鉴权）
	GetUploadURL(context.Context, *GetUploadURLRequest) (*UploadURLResponse, error)
	// 生成上传头像的上传凭证（为当前用户）
	GetAvatarUploadURL(context.Context, *GetAvatarUploadRequest) (*UploadURLResponse, error)
	// 生成上传帖子图片的上传凭证（需要指定 post_id）
	GetPostImageUploadURL(context.Context, *GetPostImageUploadRequest) (*UploadURLResponse, error)
	// 确认上传完成（保存记录到数据库）
	ConfirmUpload(context.Context, *ConfirmUploadRequest) (*ConfirmUploadResponse, error)
	// 确认头像上传完成
	ConfirmAvatarUpload(context.Context, *ConfirmAvatarUploadRequest) (*ConfirmUploadResponse, error)
	// 确认帖子图片上传完成
	ConfirmPostImageUpload(context.Context, *ConfirmPostImageUploadRequest) (*ConfirmUploadResponse, error)
	// 获取文件信息
	GetFile(context.Context, *GetFileRequest) (*UrlResponse, error)
	// 获取用户头像
	GetAvatar(context.Context, *GetAvatarRequest) (*UrlResponse, error)
	// 获取某帖的图片列表
	GetPostImages(context.Context, *GetPostImagesRequest) (*GetPostImagesResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) GetUploadURL(context.Context, *GetUploadURLRequest) (*UploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadURL not implemented")
}
func (UnimplementedFileServiceServer) GetAvatarUploadURL(context.Context, *GetAvatarUploadRequest) (*UploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvatarUploadURL not implemented")
}
func (UnimplementedFileServiceServer) GetPostImageUploadURL(context.Context, *GetPostImageUploadRequest) (*UploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostImageUploadURL not implemented")
}
func (UnimplementedFileServiceServer) ConfirmUpload(context.Context, *ConfirmUploadRequest) (*ConfirmUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmUpload not implemented")
}
func (UnimplementedFileServiceServer) ConfirmAvatarUpload(context.Context, *ConfirmAvatarUploadRequest) (*ConfirmUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmAvatarUpload not implemented")
}
func (UnimplementedFileServiceServer) ConfirmPostImageUpload(context.Context, *ConfirmPostImageUploadRequest) (*ConfirmUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPostImageUpload not implemented")
}
func (UnimplementedFileServiceServer) GetFile(context.Context, *GetFileRequest) (*UrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedFileServiceServer) GetAvatar(context.Context, *GetAvatarRequest) (*UrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvatar not implemented")
}
func (UnimplementedFileServiceServer) GetPostImages(context.Context, *GetPostImagesRequest) (*GetPostImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostImages not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call panics, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_GetUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetUploadURL(ctx, req.(*GetUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetAvatarUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvatarUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetAvatarUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetAvatarUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetAvatarUploadURL(ctx, req.(*GetAvatarUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetPostImageUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostImageUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetPostImageUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetPostImageUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetPostImageUploadURL(ctx, req.(*GetPostImageUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ConfirmUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ConfirmUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ConfirmUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ConfirmUpload(ctx, req.(*ConfirmUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ConfirmAvatarUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmAvatarUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ConfirmAvatarUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ConfirmAvatarUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ConfirmAvatarUpload(ctx, req.(*ConfirmAvatarUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ConfirmPostImageUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPostImageUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ConfirmPostImageUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ConfirmPostImageUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ConfirmPostImageUpload(ctx, req.(*ConfirmPostImageUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetAvatar(ctx, req.(*GetAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetPostImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetPostImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetPostImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetPostImages(ctx, req.(*GetPostImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUploadURL",
			Handler:    _FileService_GetUploadURL_Handler,
		},
		{
			MethodName: "GetAvatarUploadURL",
			Handler:    _FileService_GetAvatarUploadURL_Handler,
		},
		{
			MethodName: "GetPostImageUploadURL",
			Handler:    _FileService_GetPostImageUploadURL_Handler,
		},
		{
			MethodName: "ConfirmUpload",
			Handler:    _FileService_ConfirmUpload_Handler,
		},
		{
			MethodName: "ConfirmAvatarUpload",
			Handler:    _FileService_ConfirmAvatarUpload_Handler,
		},
		{
			MethodName: "ConfirmPostImageUpload",
			Handler:    _FileService_ConfirmPostImageUpload_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _FileService_GetFile_Handler,
		},
		{
			MethodName: "GetAvatar",
			Handler:    _FileService_GetAvatar_Handler,
		},
		{
			MethodName: "GetPostImages",
			Handler:    _FileService_GetPostImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file.proto",
}
