// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interaction.proto

package server

import (
	"context"

	"temp/interaction/rpc/interaction"
	"temp/interaction/rpc/internal/logic"
	"temp/interaction/rpc/internal/svc"
)

type InteractionServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedInteractionServer
}

func NewInteractionServer(svcCtx *svc.ServiceContext) *InteractionServer {
	return &InteractionServer{
		svcCtx: svcCtx,
	}
}

func (s *InteractionServer) Like(ctx context.Context, in *interaction.LikeRequest) (*interaction.CommonResp, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

func (s *InteractionServer) Favorite(ctx context.Context, in *interaction.FavoriteRequest) (*interaction.CommonResp, error) {
	l := logic.NewFavoriteLogic(ctx, s.svcCtx)
	return l.Favorite(in)
}

func (s *InteractionServer) Follow(ctx context.Context, in *interaction.FollowRequest) (*interaction.CommonResp, error) {
	l := logic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

func (s *InteractionServer) GetMyFollowing(ctx context.Context, in *interaction.GetMyFollowingRequest) (*interaction.GetMyFollowingResponse, error) {
	l := logic.NewGetMyFollowingLogic(ctx, s.svcCtx)
	return l.GetMyFollowing(in)
}

func (s *InteractionServer) GetMyFavourites(ctx context.Context, in *interaction.GetMyFavouritesRequest) (*interaction.GetMyFavouritesResponse, error) {
	l := logic.NewGetMyFavouritesLogic(ctx, s.svcCtx)
	return l.GetMyFavourites(in)
}

func (s *InteractionServer) GetPostFavoritesCount(ctx context.Context, in *interaction.GetPostFavoritesCountRequest) (*interaction.GetPostFavoritesCountResponse, error) {
	l := logic.NewGetPostFavoritesCountLogic(ctx, s.svcCtx)
	return l.GetPostFavoritesCount(in)
}
