// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"temp/post/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/posts",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts/:id",
				Handler: GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/posts/:id",
				Handler: UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/posts/:id",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts/:id/exists",
				Handler: ExistsPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/posts/:id/feature",
				Handler: FeaturePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts/:id/meta",
				Handler: MetaPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/posts/:id/pin",
				Handler: PinPostHandler(serverCtx),
			},
		},
	)
}
