apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

images:
- name: temp-auth
  newName: ghcr.io/528085390/bbs-go/auth
  newTag: sha-a1640938bd690c525e6f1ed360151f7262e4c445
- name: temp-comment
  newName: ghcr.io/528085390/bbs-go/comment
  newTag: sha-a1640938bd690c525e6f1ed360151f7262e4c445
- name: temp-file
  newName: ghcr.io/528085390/bbs-go/file
  newTag: sha-a1640938bd690c525e6f1ed360151f7262e4c445
- name: temp-gateway
  newName: ghcr.io/528085390/bbs-go/gateway
  newTag: sha-a1640938bd690c525e6f1ed360151f7262e4c445
- name: temp-interaction
  newName: ghcr.io/528085390/bbs-go/interaction
  newTag: sha-a1640938bd690c525e6f1ed360151f7262e4c445
- name: temp-post
  newName: ghcr.io/528085390/bbs-go/post
  newTag: sha-a1640938bd690c525e6f1ed360151f7262e4c445
- name: temp-search
  newName: ghcr.io/528085390/bbs-go/search
  newTag: sha-a1640938bd690c525e6f1ed360151f7262e4c445
- name: temp-section
  newName: ghcr.io/528085390/bbs-go/section
  newTag: sha-a1640938bd690c525e6f1ed360151f7262e4c445
- name: temp-user
  newName: ghcr.io/528085390/bbs-go/user
  newTag: sha-a1640938bd690c525e6f1ed360151f7262e4c445

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    namespace: temp
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 200m
          memory: 384Mi
        limits:
          cpu: 800m
          memory: 768Mi
  target:
    kind: Deployment
    name: user|auth|post|gateway
    namespace: temp
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 150m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
  target:
    kind: Deployment
    name: section|comment|interaction
    namespace: temp
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 256Mi
  target:
    kind: Deployment
    name: search|file
    namespace: temp
