// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userclient

import (
	"context"

	"temp/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExistsResp         = user.ExistsResp
	GetUserInfoRequest = user.GetUserInfoRequest
	IdRequest          = user.IdRequest
	Request            = user.Request
	Response           = user.Response
	UserInfoResponse   = user.UserInfoResponse

	User interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		GetUserInfoBy(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		UpdateUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		ExistsUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ExistsResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfoBy(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfoBy(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUser) ExistsUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*ExistsResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ExistsUser(ctx, in, opts...)
}
